server:
  port: 8090

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: studentModule
        uri: lb://student-service
        predicates:
        - Path=/student/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka