server:
  port: 8081
  
spring: 
  application:
     name : student-service
  zipkin:
    enabled: true

  datasource: 
    url : jdbc:oracle:thin:@localhost:1521/XE
    username : springboot
    password : springboot
    driver-class-name: oracle.jdbc.OracleDriver
  jpa: 
    database-platform: org.hibernate.dialect.Oracle10gDialect
    open-in-view: true
    hibernate:
      ddl-auto: none
      
    
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
 
resilience4j:
  circuitbreaker:
    configs: 
      shared:
        register-health-indicator: true 
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 40
        slow-call-rate-threshold: 40
        permitted-number-of-calls-in-half-open-state: 1
        max-wait-duration-in-half-open-state: 10s
        wait-duration-in-open-state: 10s
        slow-call-duration-threshold: 2s
        writable-stack-trace-enabled: true
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      example:
        base-config: shared      